'use client';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Check, Contact, ScanLine, Shield, WandSparkles, ArrowUp, UserPlus, FileText, Briefcase } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';
import * as React from 'react';
import { Highlight } from '@/components/highlight';
import { PlaceHolderImages } from '@/lib/placeholder-images';


const features = [
  {
    icon: <ScanLine className="w-8 h-8 text-primary" />,
    title: 'Comprehensive Vulnerability Scanning',
    description: 'Run in-depth security scans to identify a wide range of vulnerabilities, from SQL injection to XSS.',
  },
  {
    icon: <WandSparkles className="w-8 h-8 text-primary" />,
    title: 'AI-Powered Remediation Guidance',
    description: 'Get tailored, actionable advice generated by AI to fix identified security weaknesses quickly and effectively.',
  },
  {
    icon: <Shield className="w-8 h-8 text-primary" />,
    title: 'Detailed & Actionable Reporting',
    description: 'Receive easy-to-understand reports that prioritize findings, helping you focus on what matters most.',
  },
];

const howItWorksSteps = [
  {
    icon: <UserPlus className="w-10 h-10 text-primary" />,
    title: 'Sign Up & Connect',
    description: 'Create your account in seconds and provide the URL of the application you want to scan. No complex setup required.',
  },
  {
    icon: <ScanLine className="w-10 h-10 text-primary" />,
    title: 'Run Your Scan',
    description: 'With a single click, initiate a comprehensive security scan. Our engine will analyze your application for vulnerabilities.',
  },
  {
    icon: <FileText className="w-10 h-10 text-primary" />,
    title: 'Get Results & Remediate',
    description: 'Receive a detailed report with prioritized findings and AI-powered guidance to fix issues quickly and efficiently.',
  },
]

export default function Home({ searchQuery }: { searchQuery?: string }) {
  const heroImage = PlaceHolderImages.find(p => p.id === 'dashboard-hero');
  const [showBackToTop, setShowBackToTop] = React.useState(false);

  React.useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 300) {
        setShowBackToTop(true);
      } else {
        setShowBackToTop(false);
      }
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: 'smooth',
    });
  };

  return (
    <div className="flex flex-col min-h-screen bg-background">
      <main className="flex-1">
        {/* Hero Section */}
        <section className="w-full py-20 md:py-32 lg:py-40 bg-background">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12 xl:gap-16 items-center">
              <div className="space-y-6">
                <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl">
                  <Highlight query={searchQuery ?? ''}>Fortify Your Web Applications</Highlight>
                </h1>
                <p className="max-w-[600px] text-muted-foreground md:text-xl">
                  <Highlight query={searchQuery ?? ''}>CyberWall Scanner provides powerful, AI-driven security analysis to help you identify and remediate vulnerabilities before they become a threat.</Highlight>
                </p>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Button asChild size="lg">
                    <Link href="/dashboard">Get Started for Free</Link>
                  </Button>
                  <Button asChild variant="outline" size="lg">
                    <Link href="/services">Learn More</Link>
                  </Button>
                </div>
              </div>
              <div className="flex justify-center">
                {heroImage && (
                  <Image
                    src={heroImage.imageUrl}
                    alt="Cybersecurity"
                    width={600}
                    height={400}
                    className="rounded-xl shadow-2xl"
                    data-ai-hint={heroImage.imageHint}
                  />
                )}
              </div>
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section id="features" className="w-full py-20 md:py-32 bg-secondary/50">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center mb-12">
              <div className="inline-block rounded-lg bg-primary/10 px-3 py-1 text-sm font-semibold text-primary">Key Features</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                <Highlight query={searchQuery ?? ''}>Everything You Need to Secure Your Code</Highlight>
              </h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                <Highlight query={searchQuery ?? ''}>Our platform combines automated scanning with intelligent analysis to provide a complete security solution.</Highlight>
              </p>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-1 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              {features.map((feature, index) => (
                <Card key={index} className="h-full hover:shadow-lg transition-shadow bg-card">
                  <CardHeader className="flex flex-row items-center gap-4">
                    {feature.icon}
                    <CardTitle className="text-xl"><Highlight query={searchQuery ?? ''}>{feature.title}</Highlight></CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-muted-foreground"><Highlight query={searchQuery ?? ''}>{feature.description}</Highlight></p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>

        {/* How It Works Section */}
        <section id="how-it-works" className="w-full py-20 md:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center mb-12">
              <div className="inline-block rounded-lg bg-primary/10 px-3 py-1 text-sm font-semibold text-primary">How It Works</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                <Highlight query={searchQuery ?? ''}>Get Started in Three Simple Steps</Highlight>
              </h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                <Highlight query={searchQuery ?? ''}>Our intuitive platform makes it easy to start securing your web applications today.</Highlight>
              </p>
            </div>
            <div className="relative">
              <div className="absolute top-1/2 left-0 w-full h-0.5 bg-border -translate-y-1/2" aria-hidden="true"></div>
              <div className="relative mx-auto grid items-start gap-8 sm:max-w-4xl md:gap-12 lg:max-w-5xl lg:grid-cols-3">
                {howItWorksSteps.map((step, index) => (
                  <div key={index} className="flex flex-col items-center text-center gap-4 p-6 rounded-lg bg-background">
                    <div className="bg-primary/10 rounded-full p-4 mb-4 ring-8 ring-background">
                      {step.icon}
                    </div>
                    <h3 className="text-xl font-bold"><Highlight query={searchQuery ?? ''}>{step.title}</Highlight></h3>
                    <p className="text-muted-foreground"><Highlight query={searchQuery ?? ''}>{step.description}</Highlight></p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Pricing Section */}
        <section id="pricing" className="w-full py-20 md:py-32 bg-secondary/50">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center mb-12">
              <div className="inline-block rounded-lg bg-primary/10 px-3 py-1 text-sm font-semibold text-primary">Pricing</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                <Highlight query={searchQuery ?? ''}>Simple, Transparent Pricing</Highlight>
              </h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                <Highlight query={searchQuery ?? ''}>Choose the plan that's right for you. Get started for free.</Highlight>
              </p>
            </div>
            <div className="grid gap-8 lg:grid-cols-3 max-w-5xl mx-auto">
                <Card className="flex flex-col transition-transform hover:scale-105">
                    <CardHeader>
                    <CardTitle className="text-2xl">Free</CardTitle>
                    <p className="text-4xl font-bold">$0<span className="text-sm font-normal text-muted-foreground">/month</span></p>
                    </CardHeader>
                    <CardContent className="flex-1 space-y-4">
                    <ul className="space-y-2 text-muted-foreground">
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-accent" /> <Highlight query={searchQuery ?? ''}>1 User</Highlight></li>
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-accent" /> <Highlight query={searchQuery ?? ''}>Basic Scanning</Highlight></li>
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-accent" /> <Highlight query={searchQuery ?? ''}>Limited Reports</Highlight></li>
                    </ul>
                    </CardContent>
                    <div className="p-6 pt-0">
                    <Button asChild className="w-full" variant="outline"><Link href="/signup">Sign Up</Link></Button>
                    </div>
                </Card>
                <Card className="flex flex-col border-primary ring-2 ring-primary shadow-lg transition-transform hover:scale-105 relative overflow-hidden">
                    <div className="absolute top-0 right-0 bg-primary text-primary-foreground px-8 py-1 font-semibold" style={{clipPath: 'polygon(0 0, 100% 0, 100% 100%, 25% 100%)'}}>Popular</div>
                    <CardHeader className="pt-12">
                    <CardTitle className="text-2xl">Pro</CardTitle>
                    <p className="text-4xl font-bold">$49<span className="text-sm font-normal text-muted-foreground">/month</span></p>
                    </CardHeader>
                    <CardContent className="flex-1 space-y-4">
                    <ul className="space-y-2 text-muted-foreground">
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-accent" /> <Highlight query={searchQuery ?? ''}>5 Users</Highlight></li>
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-accent" /> <Highlight query={searchQuery ?? ''}>Advanced Scanning</Highlight></li>
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-accent" /> <Highlight query={searchQuery ?? ''}>AI Remediation</Highlight></li>
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-accent" /> <Highlight query={searchQuery ?? ''}>Detailed Reports</Highlight></li>
                    </ul>
                    </CardContent>
                    <div className="p-6 pt-0">
                    <Button asChild className="w-full"><Link href="/dashboard">Get Started</Link></Button>
                    </div>
                </Card>
                 <Card className="flex flex-col transition-transform hover:scale-105">
                    <CardHeader>
                    <CardTitle className="text-2xl flex items-center gap-2">Business <Briefcase /></CardTitle>
                    <p className="text-4xl font-bold">$99<span className="text-sm font-normal text-muted-foreground">/month</span></p>
                    </CardHeader>
                    <CardContent className="flex-1 space-y-4">
                    <ul className="space-y-2 text-muted-foreground">
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-accent" /> <Highlight query={searchQuery ?? ''}>Unlimited Users</Highlight></li>
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-accent" /> <Highlight query={searchQuery ?? ''}>All Pro Features</Highlight></li>
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-accent" /> <Highlight query={searchQuery ?? ''}>Team Collaboration</Highlight></li>
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-accent" /> <Highlight query={searchQuery ?? ''}>Priority Support</Highlight></li>
                    </ul>
                    </CardContent>
                    <div className="p-6 pt-0">
                    <Button asChild className="w-full" variant="outline"><Link href="/signup">Contact Sales</Link></Button>
                    </div>
                </Card>
            </div>
          </div>
        </section>

        {/* Contact Section */}
        <section id="contact" className="w-full py-20 md:py-32">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <div className="inline-block rounded-lg bg-primary/10 px-3 py-1 text-sm font-semibold text-primary mb-4"><Contact className="w-5 h-5 inline-block mr-1" />Contact Us</div>
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                <Highlight query={searchQuery ?? ''}>Get in Touch</Highlight>
              </h2>
              <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                <Highlight query={searchQuery ?? ''}>Have questions about our service or pricing? We're happy to help.</Highlight>
              </p>
              <Button asChild size="lg">
                <Link href="mailto:support@cyberwall.com">Email Us</Link>
              </Button>
            </div>
          </div>
        </section>


        {/* CTA Section */}
        <section className="w-full py-20 md:py-32 bg-secondary/50">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                <Highlight query={searchQuery ?? ''}>Ready to Secure Your Application?</Highlight>
              </h2>
              <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                <Highlight query={searchQuery ?? ''}>Sign up today and start your first scan in minutes. No credit card required.</Highlight>
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
               <Button asChild size="lg" className="w-full">
                  <Link href="/dashboard">Start Scanning Now</Link>
                </Button>
            </div>
          </div>
        </section>
      </main>

       {showBackToTop && (
        <Button
          onClick={scrollToTop}
          className="fixed bottom-8 right-8 h-12 w-12 rounded-full shadow-lg"
          size="icon"
        >
          <ArrowUp className="h-6 w-6" />
          <span className="sr-only">Go to top</span>
        </Button>
      )}
    </div>
  );
}
