
'use client';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Check, ScanLine, Shield, WandSparkles, UserPlus, FileText, Star, Quote, Mail, Info } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';
import * as React from 'react';
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from '@/components/ui/carousel';
import Autoplay from "embla-carousel-autoplay"

const features = [
  {
    icon: <ScanLine className="w-8 h-8 text-primary" />,
    title: 'Comprehensive Vulnerability Scanning',
    description: 'Run in-depth security scans to identify a wide range of vulnerabilities, from SQL injection to XSS.',
  },
  {
    icon: <WandSparkles className="w-8 h-8 text-primary" />,
    title: 'AI-Powered Remediation Guidance',
    description: 'Get tailored, actionable advice generated by AI to fix identified security weaknesses quickly and effectively.',
  },
  {
    icon: <Shield className="w-8 h-8 text-primary" />,
    title: 'Detailed & Actionable Reporting',
    description: 'Receive easy-to-understand reports that prioritize findings, helping you focus on what matters most.',
  },
];

const howItWorksSteps = [
  {
    icon: <UserPlus className="w-10 h-10 text-primary" />,
    title: 'Sign Up & Connect',
    description: 'Create your account in seconds and provide the URL of the application you want to scan. No complex setup required.',
  },
  {
    icon: <ScanLine className="w-10 h-10 text-primary" />,
    title: 'Run Your Scan',
    description: 'With a single click, initiate a comprehensive security scan. Our engine will analyze your application for vulnerabilities.',
  },
  {
    icon: <FileText className="w-10 h-10 text-primary" />,
    title: 'Get Results & Remediate',
    description: 'Receive a detailed report with prioritized findings and AI-powered guidance to fix issues quickly and efficiently.',
  },
]

const testimonials = [
  {
    name: 'Sarah J.',
    role: 'Lead Developer',
    testimonial: 'CyberWall Scanner transformed our security workflow. The AI remediation advice is a game-changer and has saved us countless hours. Highly recommended!',
    avatar: 'https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?w=50&h=50&fit=crop',
    aiHint: 'female developer',
  },
  {
    name: 'Atrarv Walavalkar',
    role: <>Founder of <a href="https://recircleprofront-3547939-15cbf.web.app/" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Recircle</a></>,
    testimonial: 'As a startup, security is critical. This tool provided us with enterprise-level scanning at a fraction of the cost. The reports are incredibly detailed yet easy to understand.',
    avatar: 'https://source.unsplash.com/rpF3p_RrE9g/50x50',
    aiHint: 'male executive',
  },
  {
    name: 'Emily Chen',
    role: 'Cybersecurity Analyst',
    testimonial: 'I was impressed by the breadth of vulnerabilities it detected. It\'s now an essential part of our CI/CD pipeline for continuous security monitoring.',
    avatar: 'https://images.unsplash.com/photo-1548544149-4835e62ee5b3?w=50&h=50&fit=crop',
    aiHint: 'female analyst',
  },
   {
    name: 'Sakharam Sarmalkar',
    role: 'Freelance Web Developer',
    testimonial: 'The best part is how educational it is. It doesn\'t just find flaws, it teaches you how to fix them securely. An invaluable tool for any developer.',
    avatar: 'https://plus.unsplash.com/premium_photo-1664203068145-b1d7d1680f6c?w=50&h=50&fit=crop',
    aiHint: 'male face',
  },
];

export default function Home() {
  const plugin = React.useRef(
    Autoplay({ delay: 4000, stopOnInteraction: true, stopOnMouseEnter: true })
  )

  return (
    <div className="flex flex-col min-h-screen bg-background">
      <main className="flex-1">
        {/* Hero Section */}
        <section className="w-full py-20 md:py-32 lg:py-40 bg-background">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12 xl:gap-16 items-center">
              <div className="space-y-6">
                <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl">
                  Intelligent Security Scanning for Modern Web Apps
                </h1>
                <p className="max-w-[600px] text-muted-foreground md:text-xl">
                  CyberWall Scanner provides powerful, AI-driven security analysis to help you identify and remediate vulnerabilities before they become a threat.
                </p>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Button asChild size="lg">
                    <Link href="/scanner">Get Started for Free</Link>
                  </Button>
                  <Button asChild variant="outline" size="lg">
                    <Link href="/#features">Learn More</Link>
                  </Button>
                </div>
              </div>
              <div className="flex justify-center items-center">
                <div className="relative flex h-64 w-64 items-center justify-center md:h-80 md:w-80">
                    {/* Animated Rings */}
                    <div className="absolute h-full w-full rounded-full bg-primary/10 animate-expand-fade" style={{ animationDelay: '0s' }} />
                    <div className="absolute h-full w-full rounded-full bg-primary/10 animate-expand-fade" style={{ animationDelay: '1s' }} />
                    <div className="absolute h-full w-full rounded-full bg-primary/10 animate-expand-fade" style={{ animationDelay: '2s' }} />
                    
                    {/* Central Shield */}
                    <Shield className="w-32 h-32 md:w-48 md:h-48 text-primary drop-shadow-[0_0_10px_hsl(var(--primary))]" />
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section id="features" className="w-full py-20 md:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center mb-12">
              <div className="inline-block rounded-lg bg-primary/10 px-3 py-1 text-sm font-semibold text-primary">Key Features</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                Everything You Need to Secure Your Code
              </h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Our platform combines automated scanning with intelligent analysis to provide a complete security solution.
              </p>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl md:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              {features.map((feature, index) => (
                <Card key={index} className="h-full hover:shadow-primary/10 hover:-translate-y-1 transition-all bg-card">
                  <CardHeader className="flex flex-col items-center text-center gap-4">
                     <div className="bg-primary/10 rounded-full p-4">
                        {feature.icon}
                    </div>
                    <CardTitle className="text-xl">{feature.title}</CardTitle>
                  </CardHeader>
                  <CardContent className="text-center">
                    <p className="text-muted-foreground">{feature.description}</p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>

        {/* How It Works Section */}
        <section id="how-it-works" className="w-full py-20 md:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center mb-12">
              <div className="inline-block rounded-lg bg-primary/10 px-3 py-1 text-sm font-semibold text-primary">How It Works</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                Get Started in Three Simple Steps
              </h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Our intuitive platform makes it easy to start securing your web applications today.
              </p>
            </div>
            <div className="relative">
              <div className="absolute top-1/2 left-0 w-full h-0.5 bg-border -translate-y-1/2 max-lg:hidden" aria-hidden="true"></div>
              <div className="relative mx-auto grid items-start gap-8 sm:max-w-4xl md:gap-12 lg:max-w-5xl lg:grid-cols-3">
                {howItWorksSteps.map((step, index) => (
                  <div key={index} className="flex flex-col items-center text-center gap-4 p-6 rounded-lg bg-background">
                    <div className="bg-primary/10 rounded-full p-4 mb-4 ring-8 ring-background">
                      {step.icon}
                    </div>
                    <h3 className="text-xl font-bold">{step.title}</h3>
                    <p className="text-muted-foreground">{step.description}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>
        
        {/* Testimonials Section */}
        <section id="testimonials" className="w-full py-20 md:py-32 bg-muted">
            <div className="container px-4 md:px-6">
                 <div className="flex flex-col items-center justify-center space-y-4 text-center mb-12">
                    <div className="inline-block rounded-lg bg-primary/10 px-3 py-1 text-sm font-semibold text-primary">Testimonials</div>
                    <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">What Our Users Say</h2>
                    <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                        Trusted by developers and security professionals worldwide.
                    </p>
                </div>
                 <Carousel
                    plugins={[plugin.current]}
                    opts={{
                        align: "start",
                        loop: true,
                    }}
                    className="w-full max-w-4xl mx-auto"
                    onMouseEnter={plugin.current.stop}
                    onMouseLeave={plugin.current.reset}
                    >
                    <CarouselContent>
                        {testimonials.map((testimonial, index) => (
                        <CarouselItem key={index} className="md:basis-1/2">
                            <div className="p-1 h-full">
                               <Card className="h-full flex flex-col justify-between p-6 bg-card/80 backdrop-blur-sm">
                                    <div>
                                        <div className="flex items-center gap-2 mb-2">
                                            {[...Array(5)].map((_, i) => <Star key={i} className="w-5 h-5 text-yellow-400 fill-yellow-400" />)}
                                        </div>
                                        <p className="text-muted-foreground italic">"{testimonial.testimonial}"</p>
                                    </div>
                                    <div className="flex items-center gap-4 mt-auto pt-4">
                                        <Image 
                                            src={testimonial.avatar}
                                            alt={testimonial.name}
                                            width={50}
                                            height={50}
                                            className="rounded-full"
                                            data-ai-hint={testimonial.aiHint}
                                        />
                                        <div>
                                            <p className="font-semibold">{testimonial.name}</p>
                                            <p className="text-sm text-muted-foreground">{testimonial.role}</p>
                                        </div>
                                    </div>
                               </Card>
                            </div>
                        </CarouselItem>
                        ))}
                    </CarouselContent>
                    <CarouselPrevious />
                    <CarouselNext />
                </Carousel>
            </div>
        </section>


        {/* Pricing Section */}
        <section id="pricing" className="w-full py-20 md:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center mb-12">
              <div className="inline-block rounded-lg bg-primary/10 px-3 py-1 text-sm font-semibold text-primary">Pricing</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                Simple, Transparent Pricing
              </h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Choose the plan that's right for you. Get started for free.
              </p>
            </div>
            <div className="grid gap-8 lg:grid-cols-3 max-w-5xl mx-auto">
                <Card className="flex flex-col transition-transform hover:scale-[1.03]">
                    <CardHeader>
                    <h3 className="text-2xl font-semibold">Free</h3>
                    <p className="text-4xl font-bold">₹0<span className="text-sm font-normal text-muted-foreground">/month</span></p>
                    </CardHeader>
                    <CardContent className="flex-1 space-y-4">
                    <ul className="space-y-2 text-muted-foreground">
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-primary" /> 1 User</li>
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-primary" /> Basic Scanning</li>
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-primary" /> Limited Reports</li>
                    </ul>
                    </CardContent>
                    <div className="p-6 pt-0">
                    <Button asChild className="w-full" variant="outline"><Link href="/scanner">Get Started</Link></Button>
                    </div>
                </Card>
                <Card className="flex flex-col border-primary ring-2 ring-primary shadow-lg transition-transform hover:scale-[1.03] relative overflow-hidden">
                    <div className="absolute top-0 right-0 bg-primary text-primary-foreground px-4 py-1 text-sm font-semibold" style={{clipPath: 'polygon(25% 0%, 100% 0%, 100% 100%, 0% 100%)'}}>Popular</div>
                    <CardHeader className="pt-12">
                    <h3 className="text-2xl font-semibold">Pro</h3>
                    <p className="text-4xl font-bold">₹4,000<span className="text-sm font-normal text-muted-foreground">/month</span></p>
                    </CardHeader>
                    <CardContent className="flex-1 space-y-4">
                    <ul className="space-y-2 text-muted-foreground">
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-primary" /> 5 Users</li>
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-primary" /> Advanced Scanning</li>
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-primary" /> AI Remediation</li>
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-primary" /> Detailed Reports</li>
                    </ul>
                    </CardContent>
                    <div className="p-6 pt-0">
                    <Button asChild className="w-full"><Link href="/purchase">Purchase</Link></Button>
                    </div>
                </Card>
                 <Card className="flex flex-col transition-transform hover:scale-[1.03]">
                    <CardHeader>
                    <h3 className="text-2xl font-semibold">Business</h3>
                    <p className="text-4xl font-bold">₹8,000<span className="text-sm font-normal text-muted-foreground">/month</span></p>
                    </CardHeader>
                    <CardContent className="flex-1 space-y-4">
                    <ul className="space-y-2 text-muted-foreground">
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-primary" /> Unlimited Users</li>
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-primary" /> All Pro Features</li>
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-primary" /> Team Collaboration</li>
                        <li className="flex items-center gap-2"><Check className="w-4 h-4 text-primary" /> Priority Support</li>
                    </ul>
                    </CardContent>
                    <div className="p-6 pt-0">
                    <Button asChild className="w-full" variant="outline"><Link href="/#contact">Contact Sales</Link></Button>
                    </div>
                </Card>
            </div>
          </div>
        </section>

        {/* Contact Section */}
        <section id="contact" className="w-full py-20 md:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <Card className="max-w-4xl mx-auto shadow-xl">
              <CardHeader className="text-center p-8">
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                  Get in Touch
                </h2>
                <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed">
                  Have questions? We're here to help.
                </p>
              </CardHeader>
              <CardContent className="p-8 pt-0">
                <div className="grid md:grid-cols-3 gap-6">
                  <Card className="flex flex-col items-center text-center p-6 hover:shadow-primary/10 hover:-translate-y-1 transition-all">
                    <div className="p-3 bg-primary/10 rounded-full mb-4">
                      <Mail className="w-8 h-8 text-primary"/>
                    </div>
                    <h3 className="text-xl font-semibold mb-1">General Inquiries</h3>
                    <a href="mailto:info@cyberwall.com" className="text-primary hover:underline">info@cyberwall.com</a>
                  </Card>
                  <Card className="flex flex-col items-center text-center p-6 hover:shadow-primary/10 hover:-translate-y-1 transition-all">
                    <div className="p-3 bg-primary/10 rounded-full mb-4">
                      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-indian-rupee text-primary"><path d="M6 3h12"/><path d="M6 8h12"/><path d="m12 17-6-6"/><path d="M6 17h12"/></svg>
                    </div>
                    <h3 className="text-xl font-semibold mb-1">Sales</h3>
                    <a href="mailto:sales@cyberwall.com" className="text-primary hover:underline">sales@cyberwall.com</a>
                  </Card>
                  <Card className="flex flex-col items-center text-center p-6 hover:shadow-primary/10 hover:-translate-y-1 transition-all">
                    <div className="p-3 bg-primary/10 rounded-full mb-4">
                      <Info className="w-8 h-8 text-primary"/>
                    </div>
                    <h3 className="text-xl font-semibold mb-1">Support</h3>
                    <a href="mailto:support@cyberwall.com" className="text-primary hover:underline">support@cyberwall.com</a>
                  </Card>
                </div>
              </CardContent>
            </Card>
          </div>
        </section>


        {/* CTA Section */}
        <section className="w-full py-20 md:py-32">
          <div className="container px-4 text-center md:px-6">
            <div className="bg-muted p-10 md:p-16 rounded-2xl border max-w-4xl mx-auto">
              <div className="space-y-4">
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                  Ready to Secure Your Application?
                </h2>
                <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Sign up today and start your first scan in minutes. No credit card required.
                </p>
              </div>
              <div className="mx-auto mt-8 w-full max-w-sm space-y-2">
                 <Button asChild size="lg" className="w-full">
                    <Link href="/scanner">Start Scanning Now</Link>
                 </Button>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
